// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmnDJXNbRtpVbfvzgwsz_-atZdT9o6Qd4',
    appId: '1:130299942118:web:fa83d03fc5dbe8fcaf5727',
    messagingSenderId: '130299942118',
    projectId: 'donaid-solution-challenge',
    authDomain: 'donaid-solution-challenge.firebaseapp.com',
    storageBucket: 'donaid-solution-challenge.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnxBLwOHYY6fTzzhj1HVeXMk4uFsKUlkc',
    appId: '1:130299942118:android:74cbb7eb51675b3baf5727',
    messagingSenderId: '130299942118',
    projectId: 'donaid-solution-challenge',
    storageBucket: 'donaid-solution-challenge.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByKWToqluUoJfbfHcGbQPxKQOzLgOb5ws',
    appId: '1:130299942118:ios:b5e6b49f9f116f91af5727',
    messagingSenderId: '130299942118',
    projectId: 'donaid-solution-challenge',
    storageBucket: 'donaid-solution-challenge.appspot.com',
    iosClientId: '130299942118-sot0tl9s6gqc7pnqg0drutrgfgtbigpe.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByKWToqluUoJfbfHcGbQPxKQOzLgOb5ws',
    appId: '1:130299942118:ios:b5e6b49f9f116f91af5727',
    messagingSenderId: '130299942118',
    projectId: 'donaid-solution-challenge',
    storageBucket: 'donaid-solution-challenge.appspot.com',
    iosClientId: '130299942118-sot0tl9s6gqc7pnqg0drutrgfgtbigpe.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
